import EU from '../../public/EU.png';


export const currencyData = {
  AED: { country: "AE", symbol: "د.إ", name: "Emirados Árabes Unidos", namecomplete: "Dirham dos Emirados Á. U." },
  AFN: { country: "AF", symbol: "؋", name: "Afeganistão", namecomplete: "Afegane Afegão" },
  ALL: { country: "AL", symbol: "L", name: "Albânia", namecomplete: "Lek Albanês" },
  AMD: { country: "AM", symbol: "֏", name: "Armênia", namecomplete: "Dram Armênio" },
  ANG: { country: "NL", symbol: "ƒ", name: "Curaçao / Sint Maarten", namecomplete: "Florim das AN" },
  AOA: { country: "AO", symbol: "Kz", name: "Angola", namecomplete: "Kwanza Angolano" },
  ARS: { country: "AR", symbol: "$", name: "Argentina", namecomplete: "Peso Argentino" },
  AUD: { country: "AU", symbol: "$", name: "Austrália", namecomplete: "Dólar Australiano" },
  AWG: { country: "AW", symbol: "ƒ", name: "Aruba", namecomplete: "Florim de Aruba" },
  AZN: { country: "AZ", symbol: "₼", name: "Azerbaijão", namecomplete: "Manat Azeri" },

  BAM: { country: "BA", symbol: "KM", name: "Bósnia e Herzegovina", namecomplete: "Marco Conversível da BIH" },
  BBD: { country: "BB", symbol: "$", name: "Barbados", namecomplete: "Dólar de Barbados" },
  BDT: { country: "BD", symbol: "৳", name: "Bangladesh", namecomplete: "Taka de Bangladesh" },
  BGN: { country: "BG", symbol: "лв", name: "Bulgária", namecomplete: "Lev Búlgaro" },
  BHD: { country: "BH", symbol: "ب.د", name: "Barém", namecomplete: "Dinar do Bahrein" },
  BIF: { country: "BI", symbol: "Fr", name: "Burundi", namecomplete: "Franco Burundês" },
  BMD: { country: "BM", symbol: "$", name: "Bermudas", namecomplete: "Dólar das Bermudas" },
  BND: { country: "BN", symbol: "$", name: "Brunei", namecomplete: "Dólar de Brunei" },
  BOB: { country: "BO", symbol: "Bs", name: "Bolívia", namecomplete: "Boliviano" },
  BRL: { country: "BR", symbol: "R$", name: "Brasil", namecomplete: "Real Brasileiro" },
  BSD: { country: "BS", symbol: "$", name: "Bahamas", namecomplete: "Dólar das Bahamas" },
  BTN: { country: "BT", symbol: "Nu", name: "Butão", namecomplete: "Ngultrum do Butão" },
  BWP: { country: "BW", symbol: "P", name: "Botsuana", namecomplete: "Pula de Botsuana" },
  BYN: { country: "BY", symbol: "Br", name: "Bielorrússia", namecomplete: "Rublo Bielorrusso" },
  BZD: { country: "BZ", symbol: "$", name: "Belize", namecomplete: "Dólar de Belize" },

  CAD: { country: "CA", symbol: "$", name: "Canadá", namecomplete: "Dólar Canadense" },
  CDF: { country: "CD", symbol: "Fr", name: "República Democrática do Congo", namecomplete: "Franco Congolês" },
  CHF: { country: "CH", symbol: "CHF", name: "Suíça", namecomplete: "Franco Suíço" },
  CLP: { country: "CL", symbol: "$", name: "Chile", namecomplete: "Peso Chileno" },
  CNY: { country: "CN", symbol: "¥", name: "China", namecomplete: "Yuan Renminbi Chinês" },
  COP: { country: "CO", symbol: "$", name: "Colômbia", namecomplete: "Peso Colombiano" },
  CRC: { country: "CR", symbol: "₡", name: "Costa Rica", namecomplete: "Colón Costarriquenho" },
  CUP: { country: "CU", symbol: "₱", name: "Cuba", namecomplete: "Peso Cubano" },
  CVE: { country: "CV", symbol: "$", name: "Cabo Verde", namecomplete: "Escudo Cabo-Verdiano" },
  CZK: { country: "CZ", symbol: "Kč", name: "Tchéquia", namecomplete: "Coroa Tcheca" },

  DJF: { country: "DJ", symbol: "Fdj", name: "Djibouti", namecomplete: "Franco Djibutiano" },
  DKK: { country: "DK", symbol: "kr", name: "Dinamarca", namecomplete: "Coroa Dinamarquesa" },
  DOP: { country: "DO", symbol: "$", name: "República Dominicana", namecomplete: "Peso Dominicano" },
  DZD: { country: "DZ", symbol: "دج", name: "Argélia", namecomplete: "Dinar Argelino" },

  EGP: { country: "EG", symbol: "£", name: "Egito", namecomplete: "Libra Egípcia" },
  ERN: { country: "ER", symbol: "Nfk", name: "Eritreia", namecomplete: "Nakfa da Eritreia" },
  ETB: { country: "ET", symbol: "Br", name: "Etiópia", namecomplete: "Birr Etíope" },
  EUR: { country: "EU", symbol: "€", name: "União Europeia", namecomplete: "Euro", flag: EU },

  FJD: { country: "FJ", symbol: "$", name: "Fiji", namecomplete: "Dólar de Fiji" },
  FKP: { country: "FK", symbol: "£", name: "Ilhas Falkland", namecomplete: "Libra das Ilhas Falkland" },
  FOK: { country: "FO", symbol: "kr", name: "Ilhas Faroe", namecomplete: "Coroa das Ilhas Faroe" },

  GBP: { country: "GB", symbol: "£", name: "Reino Unido", namecomplete: "Libra Esterlina" },
  GEL: { country: "GE", symbol: "₾", name: "Geórgia", namecomplete: "Lari Georgiano" },
  GGP: { country: "GG", symbol: "£", name: "Guernsey", namecomplete: "Libra de Guernsey" },
  GHS: { country: "GH", symbol: "₵", name: "Gana", namecomplete: "Cedi Ganês" },
  GIP: { country: "GI", symbol: "£", name: "Gibraltar", namecomplete: "Libra de Gibraltar" },
  GMD: { country: "GM", symbol: "D", name: "Gâmbia", namecomplete: "Dalasi da Gâmbia" },
  GNF: { country: "GN", symbol: "Fr", name: "Guiné", namecomplete: "Franco Guineano" },
  GTQ: { country: "GT", symbol: "Q", name: "Guatemala", namecomplete: "Quetzal da Guatemala" },
  GYD: { country: "GY", symbol: "$", name: "Guiana", namecomplete: "Dólar da Guiana" },

  HKD: { country: "HK", symbol: "$", name: "Hong Kong", namecomplete: "Dólar de Hong Kong" },
  HNL: { country: "HN", symbol: "L", name: "Honduras", namecomplete: "Lempira de Honduras" },
  HRK: { country: "HR", symbol: "€", name: "Croácia", namecomplete: "Kuna Croata" },
  HTG: { country: "HT", symbol: "G", name: "Haiti", namecomplete: "Gourde Haitiano" },
  HUF: { country: "HU", symbol: "Ft", name: "Hungria", namecomplete: "Forint Húngaro" },

  IDR: { country: "ID", symbol: "Rp", name: "Indonésia", namecomplete: "Rupia Indonésia" },
  ILS: { country: "IL", symbol: "₪", name: "Israel", namecomplete: "Novo Shekel Israelense" },
  IMP: { country: "IM", symbol: "£", name: "Ilha de Man", namecomplete: "Libra de Isle of Man" },
  INR: { country: "IN", symbol: "₹", name: "Índia", namecomplete: "Rupia Indiana" },
  IQD: { country: "IQ", symbol: "ع.د", name: "Iraque", namecomplete: "Dinar Iraquiano" },
  IRR: { country: "IR", symbol: "﷼", name: "Irã", namecomplete: "Rial Iraniano" },
  ISK: { country: "IS", symbol: "kr", name: "Islândia", namecomplete: "Coroa Islandesa" },

  JEP: { country: "JE", symbol: "£", name: "Jersey", namecomplete: "Libra de Jersey" },
  JMD: { country: "JM", symbol: "$", name: "Jamaica", namecomplete: "Dólar Jamaicano" },
  JOD: { country: "JO", symbol: "د.ا", name: "Jordânia", namecomplete: "Dinar Jordaniano" },
  JPY: { country: "JP", symbol: "¥", name: "Japão", namecomplete: "Iene Japonês" },

  KES: { country: "KE", symbol: "Sh", name: "Quênia", namecomplete: "Xelim Queniano" },
  KGS: { country: "KG", symbol: "с", name: "Quirguistão", namecomplete: "Som Quirguiz" },
  KHR: { country: "KH", symbol: "៛", name: "Camboja", namecomplete: "Riel Cambojano" },
  KID: { country: "KI", symbol: "$", name: "Kiribati", namecomplete: "Dólar de Kiribati" },
  KMF: { country: "KM", symbol: "Fr", name: "Comores", namecomplete: "Franco Comorense" },
  KRW: { country: "KR", symbol: "₩", name: "Coreia do Sul", namecomplete: "Won Sul-Coreano" },
  KWD: { country: "KW", symbol: "د.ك", name: "Kuwait", namecomplete: "Dinar Kuwaitiano" },
  KYD: { country: "KY", symbol: "$", name: "Ilhas Cayman", namecomplete: "Dólar das Ilhas Cayman" },
  KZT: { country: "KZ", symbol: "₸", name: "Cazaquistão", namecomplete: "Tenge Cazaque" },

  LAK: { country: "LA", symbol: "₭", name: "Laos", namecomplete: "Kip Laosiano" },
  LBP: { country: "LB", symbol: "ل.ل", name: "Líbano", namecomplete: "Libra Libanesa" },
  LKR: { country: "LK", symbol: "Rs", name: "Sri Lanka", namecomplete: "Rupia do Sri Lanka" },
  LRD: { country: "LR", symbol: "$", name: "Libéria", namecomplete: "Dólar Liberiano" },
  LSL: { country: "LS", symbol: "L", name: "Lesoto", namecomplete: "Loti do Lesoto" },
  LYD: { country: "LY", symbol: "ل.د", name: "Líbia", namecomplete: "Dinar Líbio" },

  MAD: { country: "MA", symbol: "د.م", name: "Marrocos", namecomplete: "Dirham Marroquino" },
  MDL: { country: "MD", symbol: "L", name: "Moldávia", namecomplete: "Leu Moldavo" },
  MGA: { country: "MG", symbol: "Ar", name: "Madagáscar", namecomplete: "Ariary Malgaxe" },
  MKD: { country: "MK", symbol: "ден", name: "Macedônia do Norte", namecomplete: "Dinar Macedônio" },
  MMK: { country: "MM", symbol: "Ks", name: "Mianmar", namecomplete: "Kyat de Mianmar" },
  MNT: { country: "MN", symbol: "₮", name: "Mongólia", namecomplete: "Tugrik Mongol" },
  MOP: { country: "MO", symbol: "P", name: "Macau", namecomplete: "Pataca de Macau" },
  MRU: { country: "MR", symbol: "UM", name: "Mauritânia", namecomplete: "Ouguiya Mauritana" },
  MUR: { country: "MU", symbol: "₨", name: "Maurício", namecomplete: "Rupia Mauriciana" },
  MVR: { country: "MV", symbol: "Rf", name: "Maldivas", namecomplete: "Rufiyaa Maldiva" },
  MWK: { country: "MW", symbol: "MK", name: "Malawi", namecomplete: "Kwacha Malauiano" },
  MXN: { country: "MX", symbol: "$", name: "México", namecomplete: "Peso Mexicano" },
  MYR: { country: "MY", symbol: "RM", name: "Malásia", namecomplete: "Ringgit Malaio" },
  MZN: { country: "MZ", symbol: "MT", name: "Moçambique", namecomplete: "Metical Moçambicano" },

  NAD: { country: "NA", symbol: "$", name: "Namíbia", namecomplete: "Dólar Namibiano" },
  NGN: { country: "NG", symbol: "₦", name: "Nigéria", namecomplete: "Naira Nigeriana" },
  NIO: { country: "NI", symbol: "C$", name: "Nicarágua", namecomplete: "Córdoba Nicaraguense" },
  NOK: { country: "NO", symbol: "kr", name: "Noruega", namecomplete: "Coroa Norueguesa" },
  NPR: { country: "NP", symbol: "₨", name: "Nepal", namecomplete: "Rupia Nepalesa" },
  NZD: { country: "NZ", symbol: "$", name: "Nova Zelândia", namecomplete: "Dólar Neozelandês" },

  OMR: { country: "OM", symbol: "ر.ع", name: "Omã", namecomplete: "Rial Omanense" },

  PAB: { country: "PA", symbol: "B/.", name: "Panamá", namecomplete: "Balboa Panamenho" },
  PEN: { country: "PE", symbol: "S/", name: "Peru", namecomplete: "Sol Peruano" },
  PGK: { country: "PG", symbol: "K", name: "Papua-Nova Guiné", namecomplete: "Kina da Papua-Nova Guiné" },
  PHP: { country: "PH", symbol: "₱", name: "Filipinas", namecomplete: "Peso Filipino" },
  PKR: { country: "PK", symbol: "₨", name: "Paquistão", namecomplete: "Rupia Paquistanesa" },
  PLN: { country: "PL", symbol: "zł", name: "Polônia", namecomplete: "Zloty Polonês" },
  PYG: { country: "PY", symbol: "₲", name: "Paraguai", namecomplete: "Guarani Paraguaio" },

  QAR: { country: "QA", symbol: "ر.ق", name: "Catar", namecomplete: "Rial Catariano" },

  RON: { country: "RO", symbol: "lei", name: "Romênia", namecomplete: "Leu Romeno" },
  RSD: { country: "RS", symbol: "дин.", name: "Sérvia", namecomplete: "Dinar Sérvio" },
  RUB: { country: "RU", symbol: "₽", name: "Rússia", namecomplete: "Rublo Russo" },
  RWF: { country: "RW", symbol: "Fr", name: "Ruanda", namecomplete: "Franco Ruandês" },

  SAR: { country: "SA", symbol: "﷼", name: "Arábia Saudita", namecomplete: "Rial Saudita" },
  SBD: { country: "SB", symbol: "$", name: "Ilhas Salomão", namecomplete: "Dólar das Ilhas Salomão" },
  SCR: { country: "SC", symbol: "₨", name: "Seicheles", namecomplete: "Rupia de Seicheles" },
  SDG: { country: "SD", symbol: "£", name: "Sudão", namecomplete: "Libra Sudanesa" },
  SEK: { country: "SE", symbol: "kr", name: "Suécia", namecomplete: "Coroa Sueca" },
  SGD: { country: "SG", symbol: "$", name: "Singapura", namecomplete: "Dólar de Cingapura" },
  SHP: { country: "SH", symbol: "£", name: "Santa Helena", namecomplete: "Libra de Santa Helena" },
  SLE: { country: "SL", symbol: "Le", name: "Serra Leoa", namecomplete: "Leone de Serra Leoa" },
  SLL: { country: "SL", symbol: "Le", name: "Serra Leoa", namecomplete: "Leone Antigo" },
  SOS: { country: "SO", symbol: "Sh", name: "Somália", namecomplete: "Xelim Somali" },
  SRD: { country: "SR", symbol: "$", name: "Suriname", namecomplete: "Dólar do Suriname" },
  SSP: { country: "SS", symbol: "£", name: "Sudão do Sul", namecomplete: "Libra do Sudão do Sul" },
  STN: { country: "ST", symbol: "Db", name: "São Tomé e Príncipe", namecomplete: "Dobra de São Tomé e Príncipe" },
  SYP: { country: "SY", symbol: "£", name: "Síria", namecomplete: "Libra Síria" },
  SZL: { country: "SZ", symbol: "L", name: "Essuatíni", namecomplete: "Lilangeni da Essuatíni" },

  THB: { country: "TH", symbol: "฿", name: "Tailândia", namecomplete: "Baht Tailandês" },
  TJS: { country: "TJ", symbol: "ЅМ", name: "Tadjiquistão", namecomplete: "Somoni do Tajiquistão" },
  TMT: { country: "TM", symbol: "m", name: "Turcomenistão", namecomplete: "Manat do Turcomenistão" },
  TND: { country: "TN", symbol: "د.ت", name: "Tunísia", namecomplete: "Dinar Tunisiano" },
  TOP: { country: "TO", symbol: "T$", name: "Tonga", namecomplete: "Paʻanga de Tonga" },
  TRY: { country: "TR", symbol: "₺", name: "Turquia", namecomplete: "Lira Turca" },
  TTD: { country: "TT", symbol: "$", name: "Trinidad e Tobago", namecomplete: "Dólar de Trinidad e Tobago" },
  TVD: { country: "TV", symbol: "$", name: "Tuvalu", namecomplete: "Dólar de Tuvalu" },
  TWD: { country: "TW", symbol: "$", name: "Taiwan", namecomplete: "Novo Dólar Taiwanês" },
  TZS: { country: "TZ", symbol: "Sh", name: "Tanzânia", namecomplete: "Xelim Tanzaniano" },

  UAH: { country: "UA", symbol: "₴", name: "Ucrânia", namecomplete: "Grívnia Ucraniana" },
  UGX: { country: "UG", symbol: "Sh", name: "Uganda", namecomplete: "Xelim Ugandês" },
  USD: { country: "US", symbol: "$", name: "Estados Unidos", namecomplete: "Dólar Americano" },
  UYU: { country: "UY", symbol: "$", name: "Uruguai", namecomplete: "Peso Uruguaio" },
  UZS: { country: "UZ", symbol: "с", name: "Uzbequistão", namecomplete: "Som Uzbeque" },

  VES: { country: "VE", symbol: "Bs", name: "Venezuela", namecomplete: "Bolívar Venezuelano" },
  VND: { country: "VN", symbol: "₫", name: "Vietnã", namecomplete: "Dong Vietnamita" },
  VUV: { country: "VU", symbol: "Vt", name: "Vanuatu", namecomplete: "Vatu de Vanuatu" },

  WST: { country: "WS", symbol: "T", name: "Samoa", namecomplete: "Tala Samoano" },

  XAF: { country: "CM", symbol: "Fr", name: "Camarões", namecomplete: "Franco CFA da África Central" },
  XCD: { country: "AG", symbol: "$", name: "Antígua e Barbuda", namecomplete: "Dólar do Caribe Oriental" },
  XDR: { country: "XX", symbol: "¤", name: "Direitos Especiais de Saque", namecomplete: "Direitos Especiais de Saque" },
  XOF: { country: "SN", symbol: "Fr", name: "Senegal", namecomplete: "Franco CFA da África Ocidental" },
  XPF: { country: "PF", symbol: "₣", name: "Polinésia Francesa", namecomplete: "Franco CFP" },

  YER: { country: "YE", symbol: "﷼", name: "Iêmen", namecomplete: "Rial Iemenita" },

  ZAR: { country: "ZA", symbol: "R", name: "África do Sul", namecomplete: "Rand Sul-Africano" },
  ZMW: { country: "ZM", symbol: "ZK", name: "Zâmbia", namecomplete: "Kwacha Zambiano" },
  ZWL: { country: "ZW", symbol: "Z$", name: "Zimbábue", namecomplete: "Dólar do Zimbábue" }
};